name: Enjin_Coin_Spigot_Plugin
description: Spigot plugin for the Enjin Coin Minecraft Framework, a platform for game assets on the Ethereum block-chain.
version: @version@-spigot
authors: [Evan "Favorlock" Lindsay, Damien Gallagher, Tobias Drewry, Enjin Coin Team]
website: https://enjincoin.io
main: io.enjincoin.spigot_plugin.Main
softdepend: [Vault]
commands:
    enj:
        description: Enjin Coin root command.
        usage: /<command> <subcommand> [args]